global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitrii_sedov'
