version: '3.3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - backnet

  elasticsearch:
    image: elasticsearch:7.3.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - backnet

  kibana:
   image: kibana:7.3.2
   container_name: kibana
   environment:
     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
   ports:
      - "5601:5601"
   networks:
      - backnet

networks:
  backnet:
    driver: bridge
