version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:${DB_DIR}
    networks:
      backnet:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - '${PORTS}/tcp'
    networks:
      - frontnet

  post:
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      - backnet
      - frontnet
  
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      - backnet
      - frontnet

volumes:
  post_db:

networks:
  frontnet:
    driver: bridge
  backnet:
    driver: bridge
