version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:${DB_DIR}
    networks:
      - backnet
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORTS}/tcp
    networks:
      - frontnet
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - backnet
      - frontnet
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - backnet
      - frontnet

volumes:
  post_db:

networks:
  backnet:
  frontnet:
