  plugin: gcp_compute
  projects:
    - otus-docker-devops
  zones:
    - "us-central1-a"
  groups:
    appserver: "'app' in name"
    dbserver: "'db' in name"
  hostnames:
    - name
  filters: []
  auth_kind: serviceaccount
  service_account_file: /home/sysadmin/docker-crs.json
  compose:
    ansible_host: networkInterfaces[0].accessConfigs[0].natIP
